import { LOCAL_USER_ID, type CampusItem } from '../features/items/item';

const SEED_ITEMS: Omit<CampusItem, 'ownerId' | 'status' | 'createdAt' | 'updatedAt'>[] = [
  {
    id: '1',
    type: 'lost',
    title: '黑色双肩包',
    location: '图书馆三楼',
    date: '2024-05-20',
    imageAssetKey: 'backpack',
    imageUri: null,
    time: '18:40',
    locationDetail: '图书馆三楼 · 自习区',
    description: '在图书馆三楼自习区落下一个黑色双肩包，内有笔记本电脑和几本教材，请拾到的同学联系我，非常感谢！',
    contact: '139 5678 1234',
  },
  {
    id: '2',
    type: 'found',
    title: '蓝色校园卡',
    location: '教学楼A栋',
    date: '2024-05-19',
    imageAssetKey: 'campus-card',
    imageUri: null,
    time: '14:30',
    locationDetail: '教学楼A栋 · 二楼走廊',
    description: '在教学楼A栋二楼走廊捡到一张蓝色校园卡，看起来是XX大学的。卡面比较新，希望早日找到主人！',
    contact: '138 1234 5678',
  },
  {
    id: '3',
    type: 'lost',
    title: 'AirPods 耳机',
    location: '体育馆',
    date: '2024-05-18',
    imageAssetKey: 'airpods',
    imageUri: null,
    time: '20:15',
    locationDetail: '体育馆 · 羽毛球场',
    description: '打完球发现 AirPods 耳机不见了，白色充电盒上有贴纸，大概是在羽毛球场附近丢的，麻烦捡到的同学联系我。',
    contact: '137 2468 1357',
  },
  {
    id: '4',
    type: 'found',
    title: '白色保温杯',
    location: '食堂一楼',
    date: '2024-05-17',
    imageAssetKey: 'thermos',
    imageUri: null,
    time: '12:05',
    locationDetail: '食堂一楼 · 靠窗餐位',
    description: '在食堂一楼靠窗的餐位上捡到一个白色保温杯，杯身有挂绳，应该是同学用餐后忘记带走的。',
    contact: '136 9876 5432',
  },
  {
    id: '5',
    type: 'lost',
    title: '一串钥匙',
    location: '操场看台',
    date: '2024-05-16',
    imageAssetKey: 'keys',
    imageUri: null,
    time: '17:30',
    locationDetail: '操场看台 · 第三排',
    description: '在操场看台第三排落下了一串钥匙，钥匙扣是蓝色的，上面有宿舍和柜子钥匙，捡到的同学请务必联系我！',
    contact: '135 1122 3344',
  },
  {
    id: '6',
    type: 'lost',
    title: '校园卡（红色）',
    location: '图书馆',
    date: '2024-05-18',
    imageAssetKey: 'card-red',
    imageUri: null,
    time: '09:20',
    locationDetail: '图书馆 · 一楼大厅',
    description: '在图书馆一楼大厅丢失一张红色校园卡，卡套是透明的，捡到的同学请联系我，谢谢！',
    contact: '188 5566 7788',
  },
  {
    id: '7',
    type: 'found',
    title: '校园卡（绿色）',
    location: '实验楼',
    date: '2024-05-16',
    imageAssetKey: 'card-green',
    imageUri: null,
    time: '15:45',
    locationDetail: '实验楼 · 302 实验室',
    description: '在实验楼302实验室捡到一张绿色校园卡，卡面有磨损，请失主联系认领。',
    contact: '150 3344 5566',
  },
  {
    id: '8',
    type: 'lost',
    title: '学生校园卡',
    location: '操场',
    date: '2024-05-15',
    imageAssetKey: 'campus-card',
    imageUri: null,
    time: '16:10',
    locationDetail: '操场 · 跑道旁',
    description: '傍晚在操场跑步时弄丢了学生校园卡，深蓝色卡面，希望好心同学捡到后联系我。',
    contact: '186 7788 9900',
  },
];

// 示例日期与内容沿用设计稿，创建时间仅用于保持确定的初始展示顺序。
export function getSeedItems(): CampusItem[] {
  return SEED_ITEMS.map((item, index) => ({
    ...item,
    ownerId: ['1', '4', '5'].includes(item.id) ? LOCAL_USER_ID : 'demo-other',
    status: item.id === '5' ? 'resolved' : 'active',
    createdAt: Date.UTC(2024, 4, 20, 12) - index * 60000,
    updatedAt: Date.UTC(2024, 4, 20, 12) - index * 60000,
  }));
}
